#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : polkit
Version  : 9
Release  : 1
URL      : file:///aot/build/clearlinux/packages/polkit/polkit-9.tar.gz
Source0  : file:///aot/build/clearlinux/packages/polkit/polkit-9.tar.gz
Summary  : PolicyKit Authorization API
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.0
Requires: polkit-bin = %{version}-%{release}
Requires: polkit-data = %{version}-%{release}
Requires: polkit-lib = %{version}-%{release}
Requires: polkit-locales = %{version}-%{release}
Requires: polkit-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : expat-dev
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(mozjs-78)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-data-Use-stateless-system-directories-for-d-bus-PAM-.patch
Patch2: 0002-pkexec-Support-a-stateless-configuration.patch
Patch3: 0003-Don-t-complain-about-etc-polkit-2-rules.d-missing.patch
Patch4: more-gc.patch

%description
OVERVIEW
========
polkit is a toolkit for defining and handling authorizations.  It is
used for allowing unprivileged processes to speak to privileged
processes.

%package bin
Summary: bin components for the polkit package.
Group: Binaries
Requires: polkit-data = %{version}-%{release}
Requires: polkit-services = %{version}-%{release}

%description bin
bin components for the polkit package.


%package data
Summary: data components for the polkit package.
Group: Data

%description data
data components for the polkit package.


%package dev
Summary: dev components for the polkit package.
Group: Development
Requires: polkit-lib = %{version}-%{release}
Requires: polkit-bin = %{version}-%{release}
Requires: polkit-data = %{version}-%{release}
Provides: polkit-devel = %{version}-%{release}
Requires: polkit = %{version}-%{release}

%description dev
dev components for the polkit package.


%package lib
Summary: lib components for the polkit package.
Group: Libraries
Requires: polkit-data = %{version}-%{release}

%description lib
lib components for the polkit package.


%package locales
Summary: locales components for the polkit package.
Group: Default

%description locales
locales components for the polkit package.


%package services
Summary: services components for the polkit package.
Group: Systemd services

%description services
services components for the polkit package.


%package staticdev
Summary: staticdev components for the polkit package.
Group: Default
Requires: polkit-dev = %{version}-%{release}

%description staticdev
staticdev components for the polkit package.


%prep
%setup -q -n polkit
cd %{_builddir}/polkit
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617204114
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-semantic-interposition -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wp,-D_REENTRANT -pipe -ffat-lto-objects"
#
export CXXFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-semantic-interposition -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects"
#
export LDFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-semantic-interposition -fno-stack-protector -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wp,-D_REENTRANT -pipe -ffat-lto-objects"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
unset CCACHE_DISABLE
export CCACHE_NODISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
unset CCACHE_NOHASHDIR
export CCACHE_HASHDIR=true
export CCACHE_CPP2=true
#
export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
## altflags1 end
%reconfigure --enable-shared --enable-static --disable-gtk-doc-html --disable-man-pages --enable-libsystemd-login --with-os-type=ClearLinux
make  %{?_smp_mflags}


%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1617204114
rm -rf %{buildroot}
%make_install
%find_lang polkit-1

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pk-example-frobnicate
/usr/bin/pkaction
/usr/bin/pkcheck
/usr/bin/pkexec
/usr/bin/pkttyagent

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Polkit-1.0.typelib
/usr/lib64/girepository-1.0/PolkitAgent-1.0.typelib
/usr/share/dbus-1/system-services/org.freedesktop.PolicyKit1.service
/usr/share/dbus-1/system.d/org.freedesktop.PolicyKit1.conf
/usr/share/gettext/its/polkit.its
/usr/share/gettext/its/polkit.loc
/usr/share/gir-1.0/*.gir
/usr/share/pam.d/polkit-1
/usr/share/polkit-1/actions/org.freedesktop.policykit.examples.pkexec.policy
/usr/share/polkit-1/actions/org.freedesktop.policykit.policy
/usr/share/polkit-1/rules.d/50-default.rules

%files dev
%defattr(-,root,root,-)
/usr/include/polkit-1/polkit/polkit.h
/usr/include/polkit-1/polkit/polkitactiondescription.h
/usr/include/polkit-1/polkit/polkitauthority.h
/usr/include/polkit-1/polkit/polkitauthorityfeatures.h
/usr/include/polkit-1/polkit/polkitauthorizationresult.h
/usr/include/polkit-1/polkit/polkitcheckauthorizationflags.h
/usr/include/polkit-1/polkit/polkitdetails.h
/usr/include/polkit-1/polkit/polkitenumtypes.h
/usr/include/polkit-1/polkit/polkiterror.h
/usr/include/polkit-1/polkit/polkitidentity.h
/usr/include/polkit-1/polkit/polkitimplicitauthorization.h
/usr/include/polkit-1/polkit/polkitpermission.h
/usr/include/polkit-1/polkit/polkitprivate.h
/usr/include/polkit-1/polkit/polkitsubject.h
/usr/include/polkit-1/polkit/polkitsystembusname.h
/usr/include/polkit-1/polkit/polkittemporaryauthorization.h
/usr/include/polkit-1/polkit/polkittypes.h
/usr/include/polkit-1/polkit/polkitunixgroup.h
/usr/include/polkit-1/polkit/polkitunixnetgroup.h
/usr/include/polkit-1/polkit/polkitunixprocess.h
/usr/include/polkit-1/polkit/polkitunixsession.h
/usr/include/polkit-1/polkit/polkitunixuser.h
/usr/include/polkit-1/polkitagent/polkitagent.h
/usr/include/polkit-1/polkitagent/polkitagentenumtypes.h
/usr/include/polkit-1/polkitagent/polkitagentlistener.h
/usr/include/polkit-1/polkitagent/polkitagentsession.h
/usr/include/polkit-1/polkitagent/polkitagenttextlistener.h
/usr/include/polkit-1/polkitagent/polkitagenttypes.h
/usr/lib/polkit-1/polkit-agent-helper-1
/usr/lib/polkit-1/polkitd
/usr/lib64/libpolkit-agent-1.so
/usr/lib64/libpolkit-gobject-1.so
/usr/lib64/pkgconfig/polkit-agent-1.pc
/usr/lib64/pkgconfig/polkit-gobject-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpolkit-agent-1.so.0
/usr/lib64/libpolkit-agent-1.so.0.0.0
/usr/lib64/libpolkit-gobject-1.so.0
/usr/lib64/libpolkit-gobject-1.so.0.0.0

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/polkit.service

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libpolkit-agent-1.a
/usr/lib64/libpolkit-gobject-1.a

%files locales -f polkit-1.lang
%defattr(-,root,root,-)

